version: '3'
services:
  # db:
  #   image: postgres
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   volumes:
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./db/data.csv:/data.csv
  #   ports:
  #     - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    # depends_on:
    #   - db
    ports:
      - "5001:5001"
    environment:
      # 配置数据库连接需要的环境变量
      DB_HOST: pg-esgdatabse-project-esgdatabase.j.aivencloud.com
      DB_PORT: "18275"
      DB_NAME: defaultdb
      DB_USER: avnadmin
      DB_PASSWORD: "AVNS_F5e6LKp-jfqdleDTmz5"
      DB_SSLMODE: require

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"